### PR TITLE
CommandPalette - Add base command palette

### LINKED ISSUE #6: Command Palette
Create a Command Palette component. The command Palette receives user input and displays operations that an application user can take. 

image

Add a Storybook Story for this component.

### PR DESCRIPTION
**Pull request by ryanlanciaux**
This PR adds the basic Command Palette component. Resolves #6

image

### CODE REVIEW

**Comment by ryanlanciaux** [comment]
@captainsafia I added a border to the input which is a departure from the design. I can remove it if that would be best but was hoping to make that area stand out a bit more.

When entering text, the border drops down to just the bottom but still has a border to show the element has focus: 

image

Please let me know what you think about this. Thanks!

**Comment by captainsafia** [comment]
@ryanlanciaux Can you increase the padding on the text box element? It feels a little tight to the text at the moment.

**Comment by ryanlanciaux** [comment]
@captainsafia Yea - it definitely feels a bit too close to those elements right now.

**Comment by ryanlanciaux** [comment]
image

@captainsafia - I made this 8px of padding. Do you think this looks better or should there be a bit more? Thanks!

**Comment by captainsafia** [comment]
Looks much better thanks! We can also readjust this a bit once we've assembled things together. That'll probably give a more realistic view of how the final piece looks.

**Comment by ryanlanciaux** [comment]
That sounds great. It could definitely make opportunities for styling adjustments a bit more clear seeing within the context of the application 😀

**Pull request merged**
